// frontend/src/components/NetworkPlot/index.tsx
import React from 'react';
import { ChartDataPoint } from '../../types/NetworkStats';
import TTLChart from './TTLChart';
import PingTimeChart from './PingTimeChart';

interface NetworkPlotProps {
  chartData: ChartDataPoint[];
  maxPoints?: number;
}

const NetworkPlot: React.FC<NetworkPlotProps> = ({ chartData, maxPoints = 300 }) => {
  return (
    <div className="charts-container">
      <TTLChart chartData={chartData} maxPoints={maxPoints} />
      <PingTimeChart chartData={chartData} maxPoints={maxPoints} />
    </div>
  );
};

export default NetworkPlot;

// frontend-vue/src/components/NetworkPlot/index.vue
<template>
  <div class="charts-container">
    <TTLChart :chart-data="chartData" :max-points="maxPoints" />
    <PingTimeChart :chart-data="chartData" :max-points="maxPoints" />
  </div>
</template>

<script setup lang="ts">
import TTLChart from './TTLChart.vue';
import PingTimeChart from './PingTimeChart.vue';
import { ChartDataPoint } from '../../types/NetworkStats';

interface Props {
  chartData: ChartDataPoint[];
  maxPoints?: number;
}

withDefaults(defineProps<Props>(), {
  maxPoints: 300
});
</script>

<style scoped>
.charts-container {
  display: flex;
  flex-direction: column;
  gap: 2rem;
}
</style>
