// frontend-vue/src/components/NetworkPlot/TTLChart.vue
<template>
  <BaseChart
    :chart-data="chartData"
    :max-points="maxPoints"
    :title="config.title"
    :data-key="config.dataKey"
    :failed-data-key="config.failedDataKey"
    :y-axis-name="config.yAxisName"
    :y-axis-domain="config.yAxisDomain"
    :line-color="config.lineColor"
    :line-name="config.lineName"
  />
</template>

<script setup lang="ts">
import BaseChart from './BaseChart.vue';
import { ChartDataPoint } from '../../types/NetworkStats';
import { CHART_CONFIG } from '../../constants';

interface Props {
  chartData: ChartDataPoint[];
  maxPoints: number;
}

defineProps<Props>();

const config = CHART_CONFIG.TTL;
</script>

// frontend-react/src/components/NetworkPlot/TTLChart.tsx
import React from 'react';
import { ChartDataPoint } from '../../types/NetworkStats';
import BaseChart from './BaseChart';
import { CHART_CONFIG } from '../../constants';

interface TTLChartProps {
  chartData: ChartDataPoint[];
  maxPoints: number;
}

const TTLChart: React.FC<TTLChartProps> = ({ chartData, maxPoints }) => {
  const config = CHART_CONFIG.TTL;

  return (
    <BaseChart
      chartData={chartData}
      maxPoints={maxPoints}
      title={config.title}
      dataKey={config.dataKey}
      failedDataKey={config.failedDataKey}
      yAxisName={config.yAxisName}
      yAxisDomain={config.yAxisDomain}
      lineColor={config.lineColor}
      lineName={config.lineName}
    />
  );
};

export default TTLChart;
